import * as web from "@/app/api/reports/[id]/chat/route";
import { mobileAuth } from "@/lib/mobile/auth";

export const runtime = "nodejs";

type Context = { params: Promise<{ id: string }> };

// The web handlers already own the chat rules (feature flag, id check, body schema, durable
// enqueue, the 409 on an invariant break). Delegating keeps one implementation; the gate in front
// supplies the 401/403 split and the fresh writer check the app relies on.

/** Durable reviewer-chat messages. The agent's reply is generated by the worker and shows up here. */
export async function GET(request: Request, context: Context): Promise<Response> {
  const gate = await mobileAuth();
  if (!gate.ok) return gate.response;
  return web.GET(request, context);
}

/** Enqueue one reviewer message `{ clientRequestId, body }` and return 202 at once. */
export async function POST(request: Request, context: Context): Promise<Response> {
  const gate = await mobileAuth({ write: true });
  if (!gate.ok) return gate.response;
  return web.POST(request, context);
}
